# Generated by Django 5.2.5 on 2025-08-23 11:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('ART', 'Arts'), ('MED', 'Medicine'), ('LAW', 'Law'), ('EDU', 'Education'), ('SCI', 'Science'), ('HUM', 'Humanities')], max_length=10)),
                ('description', models.TextField()),
                ('duration_years', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('total_credits', models.IntegerField(default=360, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(600)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_graduation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='modules', to='registration.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='registration.course'),
        ),
    ]
