# Generated by Django 5.2.5 on 2025-08-25 06:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_course_student_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_credits',
            field=models.IntegerField(default=120, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='availability'),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('ART', 'Arts')], max_length=10, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='modules', to='registration.course', verbose_name='courses'),
        ),
        migrations.AlterField(
            model_name='module',
            name='courses_allowed',
            field=models.IntegerField(default=30, verbose_name='courses allowed'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, help_text='The course the student is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='registration.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Student identification number.', max_length=20, unique=True, verbose_name='student ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the user account was created.', verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(help_text='Designates whether the user is a student.', verbose_name='student status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(help_text='Designates whether the user is a teacher.', verbose_name='teacher status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number.", max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='registration_user',
        ),
    ]
